# Generated by Django 3.0.6 on 2020-05-20 15:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Countres',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(max_length=20, unique=True, verbose_name='Страна')),
                ('date_add', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='auto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('auto', models.CharField(max_length=20, unique=True, verbose_name='Название авто')),
                ('date_add', models.DateTimeField(auto_now_add=True)),
                ('fore', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='car.Countres')),
            ],
        ),
    ]
