# Generated by Django 3.0.6 on 2020-05-20 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0002_auto_20200520_1531'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auto',
            name='auto',
            field=models.CharField(max_length=20, unique=True, verbose_name='Название модели'),
        ),
        migrations.AlterField(
            model_name='countres',
            name='country',
            field=models.CharField(max_length=20, unique=True, verbose_name='Страна'),
        ),
    ]
